/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ericleijonmarck' at '2016-06-22 13:23' with Gradle 2.13
 *
 * @author ericleijonmarck, @date 2016-06-22 13:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
